### ISSUE TITLE
Can't configure targetTimesEntities from UI

### ISSUE THREAD

**Issue by gaco79** [gaco79/octopus-energy-rates-card#2]
As title. Should be able to add dict to targetTimesEntitites

Format as
```yaml
binary_sensor.octopus_energy_target_sensor_name:
    backgroundColour: orange
    prefix: ♨️
```
